### ISSUE TITLE
RAPIDJSON_ASSERT customization guidelines

### ISSUE THREAD

**Issue by jimvonmoon** [Tencent/rapidjson#1004]
I am considering customizing `RAPIDJSON_ASSERT` to have it throw an exception in case value getters (like `GetInt()`) fail.

Currently I wasn't able to find any confirmation in docs and source code that such customization would be exception-safe. All I could find was:
```cpp
///////////////////////////////////////////////////////////////////////////////
// RAPIDJSON_ASSERT

//! Assertion.
/*! \ingroup RAPIDJSON_CONFIG
    By default, rapidjson uses C \c assert() for internal assertions.
    User can override it by defining RAPIDJSON_ASSERT(x) macro.

    \note Parsing errors are handled and can be customized by the
          \ref RAPIDJSON_ERRORS APIs.
*/
#ifndef RAPIDJSON_ASSERT
#include <cassert>
#define RAPIDJSON_ASSERT(x) assert(x)
#endif // RAPIDJSON_ASSERT
```

It might be a good idea to extend comments here to affirm users if replacing `assert()` with `throw ...` is legal by design and exception-safe. Thanks!

**Comment by pah** [comment]
Generally speaking, RapidJSON should be exception-safe (enough) to replace `RAPIDJSON_ASSERT` by an exception.  IMHO, any (currently unknown) resource leaks due to the use of exceptions in place of assertions should be seen as bugs. We do use excpetions in the regression tests, see https://github.com/miloyip/rapidjson/blob/6e81d49b/test/unittest/unittest.h#L120.

On the other hand, you might still get a call to `std::terminate` in case of failing assertions in `noexcept` functions like [this one](https://github.com/miloyip/rapidjson/blob/6e81d49b/include/rapidjson/document.h#L600):
```cpp
   explicit GenericValue(Type type) RAPIDJSON_NOEXCEPT : data_() {
      // ...
      RAPIDJSON_ASSERT(type <= kNumberType);
```

Anyway, all failing assertions indicate a **bug** in the calling code, which should be found during testing and therefore not require any runtime handling in the deployed program.  So I'm not sure if we should advertise this technique in the documentation.

For the parsing, there is an example using exceptions in the documentation of [RAPIDJSON_PARSE_ERROR_NORETURN](http://rapidjson.org/group___r_a_p_i_d_j_s_o_n___e_r_r_o_r_s.html#ga7f8c4265b2edda78568ae3338aaf1461).

**Comment by jimvonmoon** [comment]
Great, thanks for a quick response! 👍

**Comment by pah** [comment]
This is just a heads-up that we might change the requirements for customizing `RAPIDJSON_ASSERT` to be usable within an expression, see #1010 and the change in f1ba61c.
