### ISSUE TITLE
`_LIBCPP_VERSION` is not reliable for clang on windows

### ISSUE THREAD

**Issue by xylosper** [Tencent/rapidjson#1015]
RapidJSON checks `_LIBCPP_VERSION` to determine C++11 support such as rvalue reference.

However, on Windows, clang supports most of all C++11/C++14 features but it does not define `_LIBCPP_VERSION` because it does not use libc++.

**Comment by Athosvk** [comment]
A late second on this issue. It's quite easy to hack around this, defining RAPIDJSON_HAS_CXX11_RVALUE_REFS ourselves, but it's not so nice of a solution. Clang honestly shouldn't be related to _which_ standard library is used. I doubt it would hurt making it agnostic to the standard library vendor in the first place (as long as you check the version).

**Comment by miloyip** [comment]
Any suggestion?

**Comment by Bu11etmagnet** [comment]
`__clang_major__` , `__clang_minor__`, http://en.cppreference.com/w/cpp/experimental/feature_test

**Comment by Athosvk** [comment]
I'm not certain if any other standard lib vendors have defines for their standard lib version, so I guess that's a tough one. That being said, is it really necessary to double check for the standard library version if you're already guaranteed the C++ version is correct? I mean if you have the right C++version but not the correct standard lib version, you're pretty far off a correct setup in the first place. I would, honestly, remove the check for the lib version in case there's no way to check this for other standard lib implementations, simply due to the behaviour now being 'incorrect'.

**Comment by Bu11etmagnet** [comment]
Note that the standard C++ library is not necessarily tied to the compiler (e.g. clang - any version - on CentOS 7 uses the system C++ library, which is the libstdc++ which belongs to the default compiler - GCC 4.8).
