### ISSUE TITLE
syntax error: 'this'

### ISSUE THREAD

**Issue by zoncpp** [Tencent/rapidjson#1140]
Hi,
I used rapidjson in my MFC VC++ project to parse and create some json strings.
But I have an error in document.h file :
Hide   Copy Code
new (this) GenericValue(i);

error is:
Hide   Copy Code
document.h(1739): error C2059: syntax error: 'this'

I don't know how resolve this problem. 
please help me.

**Comment by Bu11etmagnet** [comment]
Which version of Visual C++ are you using?

**Comment by mzeilfelder** [comment]
Just some info as I run into the same thing.  In my case it was caused by some debug define replacing new like:
#ifdef _DEBUG
#define DEBUG_NEW new(_NORMAL_BLOCK, __FILE__, __LINE__)
#define new DEBUG_NEW
#endif
This is some trick some people use when using VisualStudio with _CRTDBG_MAP_ALLOC so it uses _malloc_dbg  for allocations to automatically show file, line info for memory leaks. But downside is that it tends to conflict with some uses of new like the one in document.h. So if a macro like this runs before including document.h one can get the error from above.
