### ISSUE TITLE
Neat json builder based on initializer_list?

### ISSUE THREAD

**Issue by crea7or** [Tencent/rapidjson#1872]
I have done some code that [builds json/value/document from the initializer](https://github.com/crea7or/rapid-builder) list with neat syntax (as some other json libraries). Do you need it? I can easily submit it to repo as addition (maybe as rapidjson utils or something like that). Not for core of course, because there is a thin transition layer.

Currenlty working syntax:

```c++ 
 const auto sample = BuildJson(
      {{"username", "my_username"},
       {"password", "my_password"},
       {"validation-factors",
        {{"validationFactors",
          Array({
                 {{"name", "remote_address"},
                  {"value", "127.0.0.1"}}
               })
          }}
      }});
```

Json builder uses writer API from rapidjson, value/document builder uses regular AddMember/PushBack's.

**Comment by miloyip** [comment]
This seems useful. I think it can be added into a contrib folder, if it is some sorts of helper. And it can then have it's own license. If put into core rapidjson, then we need to ensure it will be maintained for future.

Some comments about the current implementation:

1. RapidJSON is header only. I think the current implementation file is not too complicated and should be fine to be put in header.
2. Better to support template parameters in RapidJSON, such as encoding and allocator.
3. Some arguments seem only needs `const char*` instead of `const std::string&`.
4. Ideally no need `std::vector` or other temporary  storage.
5. Need unit tests

**Comment by crea7or** [comment]
Thank you for answer and review! License does not matter for me, so it can be changed to anything you need. 
Header only is not a problem, templated params too. std::string is suported everywhere it's needed. 
Vector is required only for the situations where we put container value into json, so it can be removed.
