### ISSUE TITLE
regenerate a Document with buffer that called ParseInsitu 

### ISSUE THREAD

**Issue by westfly** [Tencent/rapidjson#1934]
*ParseInsitu* may change raw buffer or string, It's possible to generate a **Document** with the buffer which had called **ParseInsitu** ?
some test code may below
```cpp
char m_json_msg[102400];

{
   Document d;
   if (d.ParseInsitu(m_json_msg).HasParseError()) {
   }
}
// another thread
{
   Document d;
   // error happed !!!
   if (d.ParseInsitu(m_json_msg).HasParseError()) {
   }
}
```

**Comment by dinomight** [comment]
Based on your comments, it is *not* safe to attempt to parse the same buffer in separate threads *if* you are using `ParseInsitu`. `ParseInsitu` writes to the provided buffer as it parses and I can only assume destroys the source buffer. That means if one thread modifies that buffer while another thread attempts to parse, there's a good chance you'll get parse errors. If you're really unlucky, you'll get some sort of crash as something bad happens when both threads attempt to modify the same memory.

I think even without the thread part, this won't work since the source buffer is modified. You'll probably end up with parse errors due to unmatched braces sort of thing.

**Comment by westfly** [comment]
> Based on your comments, it is _not_ safe to attempt to parse the same buffer in separate threads _if_ you are using `ParseInsitu`. `ParseInsitu` writes to the provided buffer as it parses and I can only assume destroys the source buffer. That means if one thread modifies that buffer while another thread attempts to parse, there's a good chance you'll get parse errors. If you're really unlucky, you'll get some sort of crash as something bad happens when both threads attempt to modify the same memory.
> 
> I think even without the thread part, this won't work since the source buffer is modified. You'll probably end up with parse errors due to unmatched braces sort of thing.
thx for your reply.

without thread part, call ParseInsitu  serially would work ?

**Comment by dinomight** [comment]
Remember, the source buffer has been modified. That means if you are going to reload the content into the buffer, sure, you can reuse it if done serially. If you expect the content to be the same after the first parse, then you will have problems. Just to double check, I wrote a quick test to see the behavior. After the call to `ParseInsitu`, the source buffer is modified, so you can't rely on the content being the same in future calls.
