### ISSUE TITLE
Add IsObject() check to HasMember()

### ISSUE THREAD

**Issue by grantramsay** [Tencent/rapidjson#1946]
Checking `IsObject()` before `HasMember()` is easy to overlook/forget. When parsing user data, forgetting this check can crash a process

Removing the requirement for checking `IsObject()` simplifies the interface, and reduces the boilerplate code required to parse data

_Conceptually_ asking an array if it contains an object member is nonsense, but _practically_ just returning false would save hassle, especially when the alternative is an assert

`IsObject()` is a lightweight check, so I doubt it would impact performance

**Comment by dinomight** [comment]
There is a debug assert that would fire if you attempted to call `HasMember()` on something that is not an object. Since the interface doesn't really provide a means of "failing" an API. I suppose the underlying `FindMember()` implementation _could_ return something equivalent to `MemberEnd()` , but even that method requires the type to be an object due to the union field it uses. `MemberEnd()` also has the assert. Doing the check at the `HasMember()` level just feels too high to me.

So while, yes, this could result in a runtime crash in release, a debug test around the same JSON content should result in an assertion failure alerting you to the problem. My guess is the intent of the library is that you need to ensure the thing is what you think it is before you start making assumptions about it, which seems fair to me and would be less of a performance hit if you do the check once before a series of APIs targeting the value as an `Object`.

**Comment by grantramsay** [comment]
I agree this wouldn't really work for `FindMember()`

> a debug test around the same JSON content should result in an assertion failure alerting you to the problem

When the JSON content comes from a 3rd party, you could receive anything. Adding unit tests for every combination of array vs object isn't practical

>  My guess is the intent of the library is that you need to ensure the thing is what you think it is before you start making assumptions about it

Yep agreed. This is more about not crashing when there is a safe alternative

> less of a performance hit

`bool IsObject() const { return data_.f.flags == kObjectFlag; }`
This will likely be inlined by compiler to a single `uin16_t` comparison.
The next step `FindMember()` iterates all the members doing string comparison on each one.
I think the performance hit here is negligible


Off topic: it would be nice if there was a way to validate if code is able to parse unknown data safely. i.e. a debug mode where **_`HasMember()` asserts that `IsObject()` has been called_** (same for all `GetFoo()`/`isFoo()` methods etc). This could possibly even be done through static analysis

**Comment by dinomight** [comment]
Well, if you got content that caused your system to fail, you'd write a test for that, right? ;) And if you are taking in unknown content, you should be doing a lot of upfront validation to ensure it's structured like your program expects.
> > a debug test around the same JSON content should result in an assertion failure alerting you to the problem
> 
> When the JSON content comes from a 3rd party, you could receive anything. Adding unit tests for every combination of array vs object isn't practical

There isn't really a good, safe alternative. Imagine if `HasMember` did in fact return the `EndMember`. Is that because the value wasn't an object or was it because the member wasn't there? The error messaging you provide to your upstream users would require inspecting the object further to understand the why and report it. If you look at libraries like simdjson, they provide a result type that's able to report the why while also directly providing a valid answer on success. RapidJSON isn't going to be able to do that with how big of an API break that is and with limitations enforced by the range of supported compilers (for example, supporting pre-C++11 compilers). In the end, having a straightforward answer makes the API easier to work with and understand what it's telling you.
> > My guess is the intent of the library is that you need to ensure the thing is what you think it is before you start making assumptions about it
> 
> Yep agreed. This is more about not crashing when there is a safe alternative
> 

The point I was making was that if the API provides this guarantee, then the guarantee has to spread to all APIs. While, yes, a single API call isn't a big deal, if you have to check for object on every object related call, check for array on every array call, check for int/uint/float/double/string (you get what I'm saying), the compare and branching may become significant depending on the complexity and structure of the object. The overhead of those branches will depend on the design of the specific targeted architecture which may vary in penalty (stuff like is there branch prediction, how much prediction, cost of branching, cost of an ALU op). In other words, it's a bit hard to guarantee everywhere (and that's ignoring knowing what the compiler may or may not inline). I do agree all these concerns are rather moot since most of the surrounding operations are going to drown out this small overhead.
> > less of a performance hit
> 
> `bool IsObject() const { return data_.f.flags == kObjectFlag; }` This will likely be inlined by compiler to a single `uin16_t` comparison. The next step `FindMember()` iterates all the members doing string comparison on each one. I think the performance hit here is negligible
> 

Debug builds do exactly this :). Granted, it won't report that you failed to check `IsObject`, but it will certainly get mad at you for calling invalid APIs when a value isn't an object.
> Off topic: it would be nice if there was a way to validate if code is able to parse unknown data safely. i.e. a debug mode where **_`HasMember()` asserts that `IsObject()` has been called_** (same for all `GetFoo()`/`isFoo()` methods etc). This could possibly even be done through static analysis

**Comment by grantramsay** [comment]
@dinomight @miloyip thanks for your input, I agree with most of what you've stated.
Especially that JSON Schema is the correct tool to validate unknown content
