### ISSUE TITLE
C++ 字符数组转化为json后有多余的字符

### ISSUE THREAD

**Issue by Itsposs** [Tencent/rapidjson#1975]
`//伪代码
char data[32] = "hello world!";
Document doc;
Document::AllocatorType& allocator = doc.GetAllocator();
doc.SetObject();
doc.AddMember("type", std::move(data), allocator);
StringBuffer buffer;
Writer<StringBuffer> writer(buffer);
doc.Accept(writer);
std::string msg = buffer.GetString();
printf("data: %s", msg.c_str());

show:
data: {"type": "hello world\u000\u000...\u000"}`

**Comment by dinomight** [comment]
You're trying to write a 32 character buffer when you've only provided 13 characters. The move is probably making the type appear as a `char(&)[32]` instead of a raw `char*`, so it ends up trying to print out 32 characters instead of just up to the first null. Essentially, the array reference type is implicitly convertible to a `GenericStringRef` which assumes the string length is equal to that 32 number instead of using something like `strlen` to determine string length.

I'm also not 100% sure that the `std::move` is really necessary or does what you think here, so try skipping that and see if it resolves the problem.

**Comment by Itsposs** [comment]
Thank you very much! I have resolved this problem.
