### ISSUE TITLE
Access violation in GenericValue::AddMember in low memory conditions

### ISSUE THREAD

**Issue by nperriwp** [Tencent/rapidjson#753]
In include/rapidjson/document.h:

```
//! Add a member (name-value pair) to the object.
/*! \param name A string value as name of member.
    \param value Value of any type.
    \param allocator    Allocator for reallocating memory. It must be the same one as used before. Commonly use GenericDocument::GetAllocator().
    \return The value itself for fluent API.
    \note The ownership of \c name and \c value will be transferred to this object on success.
    \pre  IsObject() && name.IsString()
    \post name.IsNull() && value.IsNull()
    \note Amortized Constant time complexity.
*/
GenericValue& GenericValue::AddMember(GenericValue& name, GenericValue& value, Allocator& allocator)
```

can cause an access violation crash if GetMembersPointer returns null.

What the code looks like now:
        Member\* members = GetMembersPointer();
    members[o.size].name.RawAssign(name);
    members[o.size].value.RawAssign(value);
    o.size++;

The code should be changed to something like:
        Member\* members = GetMembersPointer();
    if (members)
    {
        members[o.size].name.RawAssign(name);
        members[o.size].value.RawAssign(value);
        o.size++;
    }

**Comment by miloyip** [comment]
Currently RapidJSON cannot handle failure of memory allocation.
Your fix cannot help as well, because when the pointer is null, it may have already been failed in previous realloc, which cause losing data.
To prevent further working on inconsistent state and persist them, some applications choose to terminate the program by `exit()` immediately. This can be handle by using custom allocator.

**Comment by piratf** [comment]
As there are no further recommendations for now, this issue was temporarily closed.
