### ISSUE TITLE
RapidJSON NuGet package 1.1.0 update?

### ISSUE THREAD

**Issue by minasabb** [Tencent/rapidjson#774]
Hi,

The NuGet package is still at 1.0.2
https://www.nuget.org/packages/rapidjson/

When is it going to be updated to version 1.1.0?

Thanks.

**Comment by keiichi-morisato** [comment]
@miloyip 
I currently maintain a private build where the rapidjson is pushed to our local (private) corporate repository for use by our team.
If you're interested I can push the small code necessary to allow your project to maintain your project on nuget.org yourself instead of random people and stale copies.

**Comment by esrrhs** [comment]
@keiichi-morisato recently rapidjson will release a new beta version, maybe you can update it to the nuget.org
