### ISSUE TITLE
internal::StrLen should be specialized for char with std::strlen

### ISSUE THREAD

**Issue by jcelerier** [Tencent/rapidjson#845]
The compiler seems to be able to use its builtins in this case, which can precompute the size at compile time (unlike `internal::StrLen`) : 

* GCC : https://godbolt.org/g/pslUOH
* MSVC : https://godbolt.org/g/SZsbGZ
* Clang is able to optimize it : https://godbolt.org/g/kqXBJ8

This could be important when using `write.String("someString")` which must be a quite common case.

**Comment by StilesCrisis** [comment]
Sounds good to me. I've added this change as pull request #872.

**Comment by StilesCrisis** [comment]
I just added a further template trick to allow quoted strings to know their length without relying on strlen at all. Requires some SFINAE trickery but should be a win overall.

**Comment by harrywong** [comment]
Hi @StilesCrisis , I just face a problem about this pr, see #889 .
In brief, when you use a char array in a struct to store text, template auto-detect size will break the behavior the old rapidjson do. Because it will not detect the real string size at all. Maybe we can distinguish the C-style string and the char array field in a struct.

**Comment by StilesCrisis** [comment]
Removed template trick.
